#测试环境
bootdo:
  uploadPath: /home/zity/workspace/marketing-business/intelligent-hall-management-system/test/uploaded_files/
logging:
  level:
    root: info
  file:
spring:
  application:
    name: intelligent-hall-test
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://116.62.114.252:3306/consignment-master-db
    username: root
    password: Consignment@2019
    initialSize: 1
    minIdle: 3
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    #useGlobalDataSourceStat: true

#redis配置
  redis:
    database: 0
    host: 101.200.211.141
    port: 6379
    username: ziteng
    password: 123456
    timeout: 0
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
#邮件发送设置
  mail:
    host: smtp.qq.com
    username: xal@ziteng.cn
    password: cppzavsdatwscbbd
    properties:
      mail:
        smtp:
            auth: true
            starttls:
              enable: true
              required: true
#springcloud配置
eureka:
  client:
    initial-instance-info-replication-interval-seconds: 0
    instance-info-replication-interval-seconds: 1
    registry-fetch-interval-seconds: 1
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${marketing.username}:${marketing.password}@172.17.12.190:8000/eureka/
  instance:
      lease-renewal-interval-in-seconds: 5
      lease-expiration-duration-in-seconds: 5
      prefer-ip-address: true
      metadata-map:
        cluster: MAIN
#其他设置
marketing:
  username: marketing
  password: marketing2017
  self:
    host: pai.zt31.cn
#其它设置
option:
  app:
    prefix: /where/${spring.application.name}