#正式环境
bootdo:
  uploadPath: /home/zity/workspace/marketing-business/consignment-master/uploaded_files/
logging:
  level:
    root: error
    com.bootdo: info
spring:
  application:
    name: consignment-master
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://116.62.114.252:3306/consignment-master-db
    username: root
    password: Consignment@2019
    initialSize: 1
    minIdle: 3
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    #useGlobalDataSourceStat: true
#redis配置
  redis:
      host: 127.0.0.1
      port: 6379
      password:
      # 连接超时时间（毫秒）
      timeout: 10000
      pool:
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 10
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 100
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
#邮件发送设置
  mail:
    host: smtp.qq.com
    username: xal@ziteng.cn
    password: cppzavsdatwscbbd
    properties:
      mail:
        smtp:
            auth: true
            starttls:
              enable: true
              required: true
#springcloud配置
eureka:
  client:
    initial-instance-info-replication-interval-seconds: 0
    instance-info-replication-interval-seconds: 1
    registry-fetch-interval-seconds: 1
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
#      defaultZone: http://${marketing.username}:${marketing.password}@116.62.114.252:8000/eureka/
      defaultZone: http://zity:zity2019@192.168.1.191:8761/eureka/,http://zity:zity2019@192.168.1.245:8761/eureka/
  instance:
      lease-renewal-interval-in-seconds: 5
      lease-expiration-duration-in-seconds: 5
      prefer-ip-address: true
      metadata-map:
        cluster: MAIN
#其他设置
marketing:
#  username: marketing
#  password: marketing2017
  username: zity
  password: zity2019
  self:
    host: tv.zt31.cn
#其它设置
option:
  app:
#    prefix: /where/${spring.application.name}
    prefix: /tv/${spring.application.name}
  file:
    prefix: https://tv.zt31.cn/tv/${spring.application.name}/files/

#swagger配置
springfox:
  documentation:
    swagger:
      v2:
        host: tv.zt31.cn